### PR TITLE
openweather cli using python3

### LINKED ISSUE #1: Implement a command line interface to Open Weathermap API in your language of choice
Implement a command line interface to the Open Weather Map API using the language of your choice _or_ improve on the solutions already in place.

1.  **Note that you will need to create your own API key and place it in the file named `apikey.txt` at the top level.**  All *.txt files should be ignored via .gitignore file.

1. Read the [project requirements here.](https://github.com/managedkaos/openweathermap-cli/blob/master/README.md)

2. If you create a new CLI, create a new folder under the top level with the name of the language you used, starting with an Uppercase letter.  

3. Inside that folder, implement your CLI in a file named `weather` (no extension).  If the implementation must be compiled, use the language extension and add a README.md with steps for compiling the code to an executable named `weather`.

4. Update `test.sh` in the Test directory to call your script or program.

Happy hacking!

-ManagedKaos

### PR DESCRIPTION
**Pull request by nkilm**
#### Demo
image

### CODE REVIEW

**Comment by managedkaos** [comment]
Thanks! One request: can you please move your solution into a subfolder named after your username? 🙏🏾

**Comment by nkilm** [comment]
Alright!

**Comment by nkilm** [comment]
Please check I've done the requested changes

**Comment by managedkaos** [comment]
LGTM

**Pull request merged**
