### PR TITLE
Ignore only apikey.txt file instead of ignoring all .txt files

### PR DESCRIPTION
**Pull request by nkilm**
#### Files changed
- `.gitignore`

### CODE REVIEW

**Comment by managedkaos** [comment]
Please use `apikey.txt` (lowercase _`k`_) instead of `apiKey.txt` (uppercase _`K`_).

The requirements ask developers to use `apikey.txt`.  So changing the case of the `K` might break existing pulls of the code and actually commit existing files. 🤔

**Comment by nkilm** [comment]
@managedkaos Okay, I'll change it to `apikey.txt`

**Comment by nkilm** [comment]
Please check now! I changed it to `apikey.txt`
image

**Comment by managedkaos** [comment]
Merged.

**Pull request merged**
