### PR TITLE
added node-cli

### PR DESCRIPTION
**Pull request by singhalpiyush12**

### CODE REVIEW

**Comment by managedkaos** [comment]
@singhalpiyush12 Thanks for the commit!  I'm not a Node dev so I don't know but, is there a way to minimize the files that are included in the commit?  Looks like they might be libraries that the user can install independent of the code.  Is there a way to list the libs needed to run like in a manifest or similar?

**Comment by managedkaos** [comment]
Code also contains the api key :'(

**Comment by singhalpiyush12** [comment]
can i know why my code wasn't merged?

**Comment by managedkaos** [comment]
@singhalpiyush12 of course!  

1.  The commit included thousands of library files.  I'm not familiar with Node, but I'm pretty sure there is a way you can supply a manifest of the libraries needed to run your code which might only be a couple files.  Having library files in the repo makes it unnecessarily large and also adds the potential of conflicting dependencies in the future.

2. Also, the API key was included in your source code.   This isn't good for shared code where the end user would be supplying their own API key.  Also not good if your own API key is in the wild.  The requirements for the project are to read the API key from the file named `apikey.txt` located at the root of the repo.  It's not included because all *.txt files are ignored to keep keys from being stored in the repo.

I hope this helps!  Thanks so much for your interest in contributing.  I look forward to your contribution should you choose to submit another PR.

Best regards!

**Pull request closed without merging**
